### ISSUE TITLE
grpc MethodDescriptor-s as public val-s

### ISSUE THREAD

**Issue by justcoon** [akka/akka-grpc#1237]
Grpc method descriptors  (io.grpc.MethodDescriptor) are now only as private variables, in code, generated for grpc client (https://github.com/akka/akka-grpc/blob/master/codegen/src/main/twirl/templates/ScalaClient/Client.scala.txt)

Is it possible to generate them as public val-s/constants in same way as generated Serializers?

Gatling grpc plugin (https://github.com/phiSgr/gatling-grpc) using those method descriptors. In addition, for this use case, scalpb grpc generation needs to be executed.

Thanks for answer.

**Comment by raboof** [comment]
Thanks for the ping! The reason we've kept these variables private is because we're not entirely sure we want to commit ourselves to keep providing them in the future.

As a workaround I think you could add the `grpc` option to the generator and that would generate classes that provide access to the io.grpc.MethodDescriptor instances (https://github.com/akka/akka-grpc/pull/1108)

We've seen this question before, though, so perhaps we should expose the descriptors as public fields marked `@ApiMayChange` so they can be used, but we don't have to commit to keeping them long-term just yet. Would you be interested in creating a PR to that effect?

**Comment by justcoon** [comment]
@raboof thanks for answer

I tried (sbt-akka-grpc 1.0.2)

`akkaGrpcCodeGeneratorSettings += "grpc,server_power_apis"`

but it  did not generated ServiceGrpc

it is like grpc setting do nothing

I am interested in creating PR with this feature, do you have some proposal how it should look like?

my proposal:

```scala
package com.user.api

import akka.grpc.internal.Marshaller

import io.grpc.MethodDescriptor

object UserApiService extends akka.grpc.ServiceDescription {
  val name = "com.user.api.proto.UserApiService"

  val descriptor: com.google.protobuf.Descriptors.FileDescriptor =
    com.user.api.proto.UserApiProto.javaDescriptor;

  object Serializers {

    import akka.grpc.scaladsl.ScalapbProtobufSerializer

    val RegisterUserReqSerializer = new ScalapbProtobufSerializer(com.user.api.proto.RegisterUserReq.messageCompanion)
    val RegisterUserResSerializer = new ScalapbProtobufSerializer(com.user.api.proto.RegisterUserRes.messageCompanion)
  }

  object Methods {
    val RegisterUserDescriptor: MethodDescriptor[com.user.api.proto.RegisterUserReq, com.user.api.proto.RegisterUserRes] =
      MethodDescriptor
        .newBuilder()
        .setType(
          MethodDescriptor.MethodType.UNARY
        )
        .setFullMethodName(MethodDescriptor.generateFullMethodName("com.user.api.proto.UserApiService", "RegisterUser"))
        .setRequestMarshaller(new Marshaller(RegisterUserReqSerializer))
        .setResponseMarshaller(new Marshaller(RegisterUserResSerializer))
        .setSampledToLocalTracing(true)
        .build()
  }

}
```

**Comment by raboof** [comment]
> I tried (sbt-akka-grpc 1.0.2)
> 
> `akkaGrpcCodeGeneratorSettings += "grpc,server_power_apis"`
> 
> but it did not generated ServiceGrpc

Ah, that syntax is not quite right. It would either be:

```
akkaGrpcCodeGeneratorSettings += "grpc"`
akkaGrpcCodeGeneratorSettings += "server_power_apis"`
```

or:

```
akkaGrpcCodeGeneratorSettings ++= Seq("grpc", "server_powe_apis")
```

> I am interested in creating PR with this feature

Cool!

> my proposal:

> ```scala
> import akka.grpc.internal.Marshaller
> import io.grpc.MethodDescriptor
> ```

Since the namespace in this file also contains names derived from generated classes, I think it would be safer to move these imports to inside the `object` that uses them.


> ```scala
> ...
> object UserApiService extends akka.grpc.ServiceDescription {
>   ...
>   object Methods {
> ```

Maybe `MethodDescriptors`?

It's still a bit confusing that there exist both `com.google.protobuf.Descriptors.MethodDescriptor` (Scala-style, generated by ScalaPB from the official protobufs) and `io.grpc.MethodDescriptor` (Java-style, coming from the `grpc-api` libary). I agree the `io.grpc` ones are useful, though, so let's start by exposing those.

Let's mark this object with `ApiMayChange`, though?

**Comment by justcoon** [comment]
thanks for hint  (akkaGrpcCodeGeneratorSettings), with mentioned settings, it is working

in relation to  MethodDescriptors, i created PR #1250
