### ISSUE TITLE
Support raw headers for requests

### ISSUE THREAD

**Issue by richdougherty** [akka/akka-grpc#142]
akka-grpc's server implementation will need to support both modeled and raw headers when reading headers from a request. Play has recently changed to use raw headers so support for raw headers is important if we want to embed akka-grpc in Play.

From reading the akka-grpc source I believe that the code that reads the `Message-Encoding` header may need to be changed to handle raw headers as well as modeled headers. It should be OK to leave any code that emits modeled headers as it currently is.

**Comment by raboof** [comment]
Thanks for bringing this up here! I'm fairly confident we're good here, since those 'custom header' helpers are only used when generating requests, [not while parsing](https://github.com/akka/akka-grpc/pull/117#discussion_r176731909).

It would be good to have some kind of test that verifies this, though!

**Comment by richdougherty** [comment]
Good to hear. At first I thought the code below was using typed headers, but now I realise it's just using the header's string name and value:

https://github.com/akka/akka-grpc/blob/8d19ba51bd282a1bb8785f35b538b7a245e65522/runtime/src/main/scala/akka/grpc/scaladsl/GrpcMarshalling.scala#L19
