### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#157]
Would be interesting to do some benchmarking with https://grpc.io/docs/guides/benchmarking.html , but perhaps we'd first want to https://github.com/akka/akka-http/issues/1985

**Comment by patriknw** [comment]
I started looking at this. I agree that it would be good to use the same as grpc-java (and others).

I got the grpc-java/benchmarks running (after some struggle).
* Used `v1.11.0` since `v1.12.0` didn't build.
* add `skipCodegen=true` to gradle.properties
* ./gradlew :grpc-benchmarks:installDist
* cd benchmarks/build/install/grpc-benchmarks/bin
* ./qps_server --address=localhost:50051
* ./qps_client --address=localhost:50051

Next will be to understand what the benchmarks are doing :)
