### ISSUE TITLE
`UNAVAILABLE: No grpc-status found` when using `akka-http` backend

### ISSUE THREAD

**Issue by sebastian-alfers** [akka/akka-grpc#1814]
Under currently unknown conditions the following error is logged when using the `akka-http` backend:

```
   akka.grpc.GrpcServiceException: UNAVAILABLE: No grpc-status found
```

**Comment by johanandren** [comment]
I'd expect it is the client response whenever any server does not respond (UNAVAILABLE - can't be reached). Since the server could not be reached the response does not contain a grpc-status header, logic for "recovering" the response is here https://github.com/akka/akka-grpc/blob/ddc302e427dab566afa7c2b4521bb0a4caaf7285/runtime/src/main/scala/akka/grpc/internal/AkkaHttpClientUtils.scala#L275

**Comment by GreyPlane** [comment]
@johanandren during implements http transcoding for akka grpc, I was found the possible reason, and I think it's a bug or design flaw.

AkkaHttpClient always check if "grpc-status" exists and equal to "0".
https://github.com/akka/akka-grpc/blob/78210d82c98c7f77a7a1d9b7a7ebbfe9b61abd7c/runtime/src/main/scala/akka/grpc/internal/AkkaHttpClientUtils.scala#L271C1-L271C1

NettyClient seems doesn't check it.
https://github.com/akka/akka-grpc/blob/78210d82c98c7f77a7a1d9b7a7ebbfe9b61abd7c/runtime/src/main/scala/akka/grpc/internal/UnaryCallAdapter.scala#L34

Also I manually inspect the trailers headers, it doesn't contain `grpc-status=0` for unknown reason, since according to the [document](https://github.com/grpc/grpc/blob/4c16e6b68f38c8b93faa39cdbbf481f325a3439e/doc/http-grpc-status-mapping.md?plain=1#L29), there should be explicit grpc-status for successful request.

**Comment by GreyPlane** [comment]
> Since the server could not be reached the response does not contain a grpc-status header

In my case, there is no way that server cannot be reached since after I changed validation logic it just works fine.

I think I can provide reproduction if needed.

**Comment by johanandren** [comment]
If there is no grpc status in the response, it seems the error is correct?

**Comment by johanandren** [comment]
So definitely interesting to know if/when the Akka gRPC server emits such a response.

**Comment by GreyPlane** [comment]
uh, I think I've missed something, after experiments with client, it's works fine with AkkaHttpClient though I do find that NettyClient's `onClose` callback doesn't contains any trailer.

sry for misleading, I will continue to investigate when to put TrailerOK into response

**Comment by GreyPlane** [comment]
I found the reason why, since I was using generated grpcHandler directly(without network), HttpEntity is Strict instead of Chunked, so codes inside `responseToSource` doesn't retrieve trailer from `attributes`, so it's lost.

https://github.com/akka/akka-grpc/blob/78210d82c98c7f77a7a1d9b7a7ebbfe9b61abd7c/runtime/src/main/scala/akka/grpc/internal/AkkaHttpClientUtils.scala#L222

I think it's OK to change it to retrieve trailer from attributes.

**Comment by jtjeferreira** [comment]
I implemented the suggested fix in https://github.com/akka/akka-grpc/pull/1906
