### ISSUE TITLE
Use a gRPC client in a Play application

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#208]
Would it suffice to describe the client in configuration (#151) - can we then make the actual client available through dependency injection as is 'native' in Play?

Progress:
* [x] Scala codegen (#272)
* [x] Java codegen
* [ ] Documentation (in Play, see omnidoc)
* [ ] Java example project (perhaps based on https://github.com/richdougherty/play-grpc-experiment)
* [ ] Scala example project

**Comment by johanandren** [comment]
If we can figure out a way to hook in logic automagically we would still need the user to specify what host+port or service name to use, I'm guessing we cannot assume that there will always be a 1:1 between service type and host you'd want to connect to either.

I wonder if it is maybe best to just provide a sample of how to bind it for injection, and one sample for how to create the client ad hoc in a controller instead of adding API for this?

**Comment by raboof** [comment]
#272 already reads that information from the configuration to make the client available for injection via DI without any further code.

Indeed there could be situations where it is not possible to put host+ip/name in the config, in that case you could create the client 'manually' (like with normal Akka gRPC).

Seems like a reasonable compromise to me?

**Comment by johanandren** [comment]
Aha, I missed out on the `ClientProvider` there. I see, clever. And that module will be usable from both Scala and Java so no "Java codegen" needed, only docs?

**Comment by johanandren** [comment]
If we could have a pre-made `Module` that picks up the generated list of clients from somewhere else, rather than generating the `Module` (which play autoloaders but would potentially conflict with the manual `Module` created by the user) that could make it possible to not have to add any extra config to hook the clients in.

**Comment by raboof** [comment]
I'm not *sure* the `ClientProvider` is usable for Java, finding out and adding Java codegen if needed is one of the open tasks for this issue.

**Comment by raboof** [comment]
I didn't find a way to make the generated clients discoverable so we can load them all from one `Module`, so far I've decided to live with the fact that the user needs to manually enable each generated client `Module` in the `application.conf`. Would definitely be neat if we can avoid it though ;).

**Comment by johanandren** [comment]
Just saw here now that the plan was to add docs in the Play documentation, I just added such docs on the Akka gRPC side. 

Hard to do a PR to play with docs before we have a release of akka-grpc though, unless we are ok with non-validated/compiled docs code ofc.

**Comment by johanandren** [comment]
Created separate tickets to track the in-play docs and the example projects.
