### ISSUE TITLE
Client close doesn't kill stream on server

### ISSUE THREAD

**Issue by peteremiljensen** [akka/akka-grpc#212]
I've a question. The server streams out stock quotes to a client.
But I can't seem to close the stream again. If calling `client.close` on the client-side, then the server stil streams quotes. It only stops if I terminate the client.

Is client.close not closing any living connections? Or am I misunderstanding something?

Thank you :)

**Comment by raboof** [comment]
Hi Peter, thanks for the feedback! It is indeed correct that `shutdown` will do an orderly shutdown in which preexisting calls continue but new calls are immediately cancelled.

Can you tell a bit more about your use case? Typically I'd say gRPC clients might be long-running processes, what is your reason for closing it? Are you winding down the entire application? Would you want/expect to cancel both existing and new calls to be shut down on close?

**Comment by peteremiljensen** [comment]
Hi Arnout.
Thanks for the quick reply.

I my use case the client should ideally also be long-running. However, I have a variable amount of actors that get spawned at different times subscribing to multiple different quotes. And they also get torn down frequently. 

But, when all the actors using a specific quote stops, I would like to be able to stop the specific quote currently streaming.
Therefore, as a last resort I tried closing everything with `client.close`, which makes sense to be long-living :)
Is there a way to stop particular streams end-to-end? I tried failing the stream using `KillSwitches`, but that didn't close the stream on the server.

I hope I'am clear. Otherwise just ask :)
Thanks

**Comment by raboof** [comment]
I think ideally terminating the stream should indeed close it all the way to the server - it's entirely possible that that is not currently the case yet, but I think I'd consider that a bug - possibly also related to the changes currently going on in #201.

**Comment by peteremiljensen** [comment]
Yes. Unfortunately, it doesn't seem to close the stream on the server.
But I'm on release v0.1 and not the master branch.

**Comment by patriknw** [comment]
I started looking at this.

It's correct that the streaming calls continue when after we have done `channel.shutdown`. Otherwise we should use `channel.shutdownNow`.

We could also install KillSwitch in the streams if that is a more graceful way to close things.

I'm not sure what we would want to support?

* shutdownNow
* shutdown
* shutdown + KillSwitch

Perhaps the full graceful shutdown (without KillSwitch) might be difficult to implement later when we switch to Akka HTTP client?

I think I'll start by simply changing it to `shutdownNow`.

This is perhaps also related to my comment about exposing the client close state in https://github.com/akka/akka-grpc/pull/260/files#r199136901

When we are at it I think we should call channel.shutdownNow when the actor system has terminated.

**Comment by peteremiljensen** [comment]
Furthermore, it would be nice if I could close a specific stream without closing the client. Right now if I KillSwitch an infinite stream, it continues streaming on the server-side

**Comment by peteremiljensen** [comment]
Sorry, I can confirm that KillSwitching works for stream

**Comment by raboof** [comment]
@peteremiljensen I think #264 should resolve the issue - feel free to reopen (or open a new ticket) when you have any further comments though!

**Comment by peteremiljensen** [comment]
Sounds good. Than you very much
