### ISSUE TITLE
Decouple client settings from Netty specifics

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc#225]
So that we can easily migrate to Akka HTTP client when we have HTTP2 support there

**Comment by raboof** [comment]
:+1:, I think we should make sure to support at least everything in the `CallCredentials` (perhaps even supply methods for easily applying `CallCredentials` that may come from a library)

**Comment by patriknw** [comment]
I'm trying to understand what we would like to do here.

We have `GrpcClientSettings`, which makes it possible to define `CallOptions`. Looks like `CallOptions` is rather specific implementation details of grpc-java and perhaps not something we would like to expose.

`CallCredentials` is more interesting and I think `GrpcClientSettings` should have `withCallCredentials`. I don't think we should hide or abstract `CallCredentials` because there are library implementations of it that we might want to support, e.g. `GoogleAuthLibraryCallCredentials` that is included in `grpc-auth`.

Another thing is if there are things in `NettyChannelBuilder` or `ManagedChannelBuilder` that we want to expose in `GrpcClientSettings`. The only candidate I can find is `ManagedChannelBuilder.userAgent`. What else?

**Comment by patriknw** [comment]
I see a risk with exposing too much, because when we switch underlying implementation we might have trouble supporting those or want to have slightly different settings. I think we should be conservative with the "nice to have" settings. Then I'd rather support a backdoor exposing the underlying implementation specific settings but make it clear that it will change.

**Comment by raboof** [comment]
Done in #245
