### ISSUE TITLE
Response transformation in the power-user API

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-grpc#229]
Sorry that I didn't get to finish explaining [my comment on #201](https://github.com/akka/akka-grpc/pull/201#issuecomment-390069982) before it was merged.

@johanandren you said:

> Hmm, I still don't get it, why would a special type with transformations be better than just having a `Future[ResponseAndHeadersType]`/`CompletionStage<ResponseAndHeadersType>` which you can transform in exactly the same way as all your other async thingies and that you already know the API of?

Because you don't get the `Future` until you invoke the call, so there's no way to write a function that transforms the result of a call without also invoking it, and therefore no way to compose functions that transform the result of a call.

Having to write separate functions to transform the request and transform the response isn't a perfect substitute, because then you can't separate construction of the call chain from the invocation of it. Part of the value of having a lifted representation is that you can express "I don't want to invoke this now, but when it _is_ invoked, I want to attach this behaviour to the response handling" and get back a new lifted representation that encapsulates it (higher-order processing of the RPC calls).

Let's say I want to write a function that wraps a gRPC request so that when it is invoked it will log the request and response bodies. AFAICT, the only way to do that with the API currently is to extend `SingleResponseRequestBuilder` or `StreamResponseRequestBuilder`, which are annotated with `@DoNotInherit`.

I don't know how important this capability is, but it is supported by both the Lagom service API and the [standard gRPC Java client](https://grpc.io/grpc-java/javadoc/io/grpc/ClientInterceptor.html).

**Comment by johanandren** [comment]
Isn't that perfectly doable just using the language capabilities instead adding api surface for it?
```
def transformResponseLater(transformResponse) = 
  param => client.someCall(param).map(transformResponse)
```

The linked `ClientCallInterceptor` is about transforming the request (by adding headers etc), so that matches the `RequestBuilder` pretty well, so I don't see how that maps the response except for possibly completely changing which gRPC method is actually invoked.

I think we can wait and see if this is an actual problem that pops up and add it to the API when that happens instead of guessing that it is important and keep the API surface as minimal as possible to start with. WDYT?
