### ISSUE TITLE
Log while generating

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#257]
It'd be nice to introduce some API for logging while generating: for example when generating the Play server, it'd be nice to log that the user is expected to implement `FooService` in `controller.FooServiceImpl` and add `-> /${FooService.name} ${fooServiceImplFqdn}` to his `conf/routes`

**Comment by johanandren** [comment]
Seems hard to achieve without upstream changes in protocbridge, PB sbt plugin expects a list of generators as a `settingsKey`, a generator has a `run` method that only accepts an array of bytes so we need to inject a logging facility through the constructor of the generators, however, we can only access the sbt logger from a `taskKey` :/ so that's a no-go

**Comment by raboof** [comment]
Hmm you're right - thanks for digging!

Instead of passing in a logger, the other option would be to include something in the result. It looks `CodeGeneratorResponse` only has a field for errors, not for 'informational' output, though... seems like the best we can do is make sure our docs and error messages when not finding things are great, then ;).

I guess we should just close this issue then?

**Comment by johanandren** [comment]
Stand back and cover your eyes, hacking my way past this obstacle!
