### ISSUE TITLE
Disambiguate 'service name' in client config/settings

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#403]
In the client config/settings, we're using the term 'service name' for 2 distinct concepts: the 'service name' derived from the `.proto` service definition (e.g. `helloworld.GreeterService`), and the 'service name' that is used to look up the service endpoints through Service Discovery.

A service configuration can look like this:
```
akka.grpc.client {
  "project.WithSpecificConfiguration" {
    service-discovery {
      service-name = "my-service"
    }
    host = "my-host"
    port = 42
    override-authority = "google.fr"
    deadline = 10m
    user-agent = "Akka-gRPC"
  }
}
```

Here 'project.WithSpecificConfiguration' is the 'service name' as derived from the `.proto`, where `my-service` is the service name to use when looking up endpoints through service discovery.

I think in the code `GrpcClientSettings.name` should be the 'service name' as derived from the `.proto`, and we should keep track of the service name for discovery separately.

Currently `GrpcClientSettings` can be service-agnostic. That suggests either `GrpcClientSettings.name` should become an `Option`, or we should drop service-agnostic `GrpcClientSettings` and only allow service-specific `GrpcClientSettings`. Both seem like acceptable solutions to me, but I haven't tried them out so I'm not sure which would have most impact.

**Comment by raboof** [comment]
Actually we seem to consistently fill `GrpcClientSettings.serviceName` with the name used for service discovery, so this might be fine.

Perhaps good to clarify this in the comment, and double-check that creating a `GrpcServiceConfig` with static discovery (host/port) works even though no service-name needs to be specified in that case.

**Comment by raboof** [comment]
Ah, service-name defaults to an empty string and there is a test to check it.

Looks good then :laughing:

**Comment by ignasi35** [comment]
There's other situations that I think would justify this naming review:

 - in Lagom the name of the deployment unit (purposedly avoiding the word `service`) is taken from the Lagom Service Descriptor.
 - when gRPC capabilities are added into a Lagom _deployment unit_, then there are two competing names: (1) Lagom Service Descriptor vs (2) the gRPC name. Lagom always chooses (1) as a name.

As a consequence, clients will have to use:

```scala
  lazy val settings = GrpcClientSettings
     .connectTo("hello-srvc", serviceDiscovery)
  // "hello-srvc" is the name of the lagom service descriptor.
```

instead of 

```scala
  lazy val settings = GrpcClientSettings
     .connectTo(MyGreetingsProtoService.name, serviceDiscovery)
```

Maybe `registryName` or `registeredName` (as in `the name under which this is registered on a service registry`) may help reduce the use of `serviceXyz`.
