### ISSUE TITLE
More idiomatic Play integration

### ISSUE THREAD

**Issue by ctoomey** [akka/akka-grpc#420]
I lead a team of long-time Play Scala  developers and we're about to start using grpc instead of REST for new APIs, as I've been discussing in #179.

Currently the auto-generated akka-grpc Play handler that wraps the grpc service method implementations returns a `Future[HttpResponse]` rather than an idiomatic Play `EssentialAction`. This means among other things that Play `Filter`s don't get called on each request as they do for REST calls, and so cross-cutting Play functionality like access logging provided by filters doesn't work.

To gain back such functionality for grpc requests, developers would need to not only port their Play filters to some new home-grown filter-like interface (since a replacement isn't provided for Play filters by akka-grpc), but also design and implement a home-grown filter chain interface.

At the very least akka-grpc should provide a Play integration that supports the existing Play idioms in addition to one like the current that doesn't.

I've taken the existing auto-generated code and akka-grpc code base and modified both so as to have grpc service implementations wrapped to return `EssentialActions` and verified that our filters work as expected. I'd love to contribute these changes back either as a replacement for or additional option for Play users. What do you say?

**Comment by johanandren** [comment]
Sounds like it makes sense, please do PR so we can look at and discuss the details!

**Comment by ignasi35** [comment]
There are several possible approaches:

1. add a capability in `akka-grpc` for request filtering
   1. make it low-level (more familiar to akka-http users). Using `Directive`s  (as hinted in #179)
   2. make it high-level (more familiar to play users). In this case, I think we should still make it play-agnostic and part of the `akka-grpc` library. Maybe refactoring `PlayRouter` to inject akka-grpc filters?
2. improve [Play's filtering code](https://github.com/playframework/playframework/blob/da68fc546da305b8fc215d0b8ad53b644b9b843c/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L222) so all requests are filtered (not just `EssentialAction`'s) 

 - - - - - - - 

As discussed internally, when adding a filter on some akka-grpc router in a Play Application there would be some limited features:

* the filter MAY block or pass the request
* the filter MAY NOT alter the request (any modification will be ignored). The reason for this limitation is that the generated code in Akka-gRPC ignores the play request and uses the _raw_ akka-http request.

 - - - - - - - 

The final concern, from a Play user point of view, is how would filters be enabled/injected. I haven't given any thought.

**Comment by ignasi35** [comment]
@ctoomey looking forward to your code.

**Comment by marcospereira** [comment]
Hey @ctoomey, thanks for starting this conversation.

I think it is not only about the filters, but all the other parts involved in how Play handles a request. There are filters involved, but also error handlers, request handlers and action composition. Having the code based on `EssentialAction` (or maybe even `Action`) will integrate grpc support with all these things.

Regarding what @ignasi35 said:

> the filter MAY NOT alter the request (any modification will be ignored). The reason for this limitation is that the generated code in Akka-gRPC ignores the play request and uses the raw akka-http request.

This may result in an *surprising* API since in Play filters can do something like `next(request.withHeader("My-Header", "Value")`. What is the reason to not alter the request at all?

------

Disclaimer: I need to catch up with the discussion on #179.

**Comment by raboof** [comment]
I gave this some more thought. To answer @marcospereira's last question: I think in the current implementation altering the Play request in a Play filter will not have any effect, because the `AkkaHttpHandler` passes the akka-http `HttpRequest` directly to the handler, ignoring the `taggedRequestHeader` and `requestBodySource` in this case (https://github.com/playframework/playframework/blob/7f7ee5cdb53cc879b741a474148850458d348520/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L300). I'm not completely familiar with the way Play works, but it looks like the `taggedRequestHeader` would contain the values possibly updated by filters?

So far we chose not to do a 'roundtrip' (start with Akka HTTP model, convert to Play model, allow filters to make changes to Play model, convert Play model back to Akka HTTP model, pass Akka HTTP model to route), partly because eventually the Akka HTTP model may be extended so that it can replace the current Play model entirely (https://github.com/akka/akka-http/issues/1500) which would harmonize all this.

I see roughly 4 approaches here:
* Drop `AkkaHttpHandler` and write this code in terms of Play `Action`s instead. The disadvantage is that this forces us to always do the 'roundtrip' both for the request and for the response.
* Instead of writing a Play filter, write the equivalent code in terms of the Akka HTTP model and provide a way to put this around the (in the akka-grpc case generated) Akka HTTP code. This avoids the 'roundtrip'. For convenience we could provide an adapter to use a Play filter here after all, at the cost of doing the roundtrip in that case. 
* Keep writing Play filters, and carrying over (at least some of) the values from the possibly-adapted Play model to the Akka HTTP request before passing it to the `AkkaHttpHandler`.
* Avoid implementing this feature until we can use the Akka HTTP model for everything and don't need a separate Play model at all anymore.

I guess we can't really get away with option '4' ;). I think we'd like to avoid always having to do the 'roundtrip' both for the request and the response, disqualifying option '1'.

This leaves option '2' and '3': '3' is the easiest to do right now, but I wonder if '2' perhaps does more to pave the way for future harmonization. WDYT?

**Comment by raboof** [comment]
AFAIU, the roundtrip Play does for every request is: "Akka HTTP Request -> Play request -> Play response -> Akka HTTP Response". That is indeed inevitable and OK. However, if we would go for "option 1", it would be "Akka HTTP Request -> Play request -> Akka HTTP Request -> Akka HTTP Response -> Play Response -> Akka Http Response".

Of course @ctoomey might not want to have to wait until Play 3 :), and indeed perhaps we can find a way to do "option 1" without introducing too much churn as an intermediate solution for Play 2.x.

**Comment by ctoomey** [comment]
See PR #447 .

**Comment by raboof** [comment]
Super happy to have this in - thanks @ctoomey!!

**Comment by enzeart** [comment]
@raboof @ctoomey is there any documentation on how this works?

**Comment by ctoomey** [comment]
Sorry @enzeart I'm not sure where the documentation for it is, I couldn't find it in the https://github.com/playframework/play-grpc repo. You can find the setting to use to enable it referenced in [these files](https://github.com/search?q=repo%3Aapache%2Fpekko-grpc%20use_play_actions&type=code); you set that in the same way as you'd set `server_power_apis` as mentioned [here](https://pekko.apache.org/docs/pekko-grpc/current/buildtools/sbt.html#generating-server-).

**Comment by enzeart** [comment]
@ctoomey thanks for your reply. I was able to find that part before making the post. My main issue is that I'm getting an exception with the Router I've implemented:

`play.api.PlayException: Execution exception[[NotImplementedError: Unexpected response entity type: org.apache.pekko.http.scaladsl.model.HttpEntity$Strict]]`

Here is how I'm setting up the offending router:

```scala
@Singleton

class GitlabServiceRouter @Inject() (
    cacheConfig: CacheConfig,
    cache: AsyncCacheApi,
    groupService: GroupService,
    controllerComponents: ControllerComponents
)(implicit actorSystem: ActorSystem, override val executionContext: ExecutionContext)
    extends AbstractGitlabServicePowerApiRouter(
      actorSystem,
      controllerComponents.parsers,
      controllerComponents.actionBuilder
    )
    with GrpcServiceHelpers
    with Logging
```

The PlayRouterUsingActions.pekkoToPlayResp method that does the translation between HTTP entity types appears to only handle chunked responses. Any guidance on how to fix this error would be greatly appreciated.

**Comment by ctoomey** [comment]
Sorry @enzeart I'm not sure why the strict entity type support wasn't implemented, that was not an area I worked on.

Theoretically that should be easy to implement given that it's simpler than chunked, so you might consider taking a crack at it and opening a PR.

**Comment by enzeart** [comment]
> Sorry [@enzeart](https://github.com/enzeart) I'm not sure why the strict entity type support wasn't implemented, that was not an area I worked on.
> 
> Theoretically that should be easy to implement given that it's simpler than chunked, so you might consider taking a crack at it and opening a PR.

@ctoomey it looks like there were some upstream changes in akka-grpc to how unary requests are handled: https://github.com/apache/pekko-grpc/commit/fa341ccd42fd31fb73ff0e23af33aaefa0d9839c

I was able to get something working and currently have an open pull request: https://github.com/playframework/play-grpc/pull/608
