### ISSUE TITLE
Interceptor for logging

### ISSUE THREAD

**Issue by leozilla** [akka/akka-grpc#526]
I am searching for a way to log the messages received on both the server and the client.
According to grpc-java it is done by implementing a `io.grpc.ServerInterceptor` but I dont find a way to add such interceptors.
How would I implement this?

**Comment by johanandren** [comment]
This is not grpc-java so you cannot use interceptors. 

You should be able to wrap the server with arbitrary Akka HTTP logic though, I'm afraid we don't have any samples showing that yet. Since the handler factory creates a `HttpRequest` to `HttpResponse` function you could wrap that with your own function doing arbitrary logic.

**Comment by jrouly** [comment]
@johanandren if I'm understanding you correctly, wrapping the handler factory seems focused on server-side interceptors.

Is there a preferred solution for client-side interceptors? e.g., if I want to decorate outbound RPC with logging, tracing, etc.

**Comment by bit-void** [comment]
Just want to add to this. Most other languages support interceptors, server side/client side and these are very useful in the context of a grpc request to transform them on the fly.

**Comment by dboreham** [comment]
This is an old issue, but Google still finds it for folks pulling their hair out. So figured it was worth mentioning this now exists: https://doc.akka.io/docs/akka-grpc/current/server/akka-http.html#method-to-log-handle-and-recover-each-rpc
