### ISSUE TITLE
Usage of deprecated javaGenerateEqualsAndHash

### ISSUE THREAD

**Issue by leozilla** [akka/akka-grpc#540]
When I compile my protos I get a lot of the following warnings for the generated google `FileOptions.scala` class.
```
/target/scala-2.12/src_managed/main/com/google/protobuf/descriptor/FileOptions.scala:306:46: value javaGenerateEqualsAndHash in class FileOptions is deprecated: Marked as deprecated in proto file
[warn]       var __javaGenerateEqualsAndHash = this.javaGenerateEqualsAndHash
```
Is this a known "issue"? (cos I havn't found an open/closed issue for it)
Is there some way to workaround this or surpress this warning?

**Comment by raboof** [comment]
Thanks for raising this question. What is going on is that this file is generated from the google `.proto` definition at https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L343, and is marked 'deprecated' there.

We use [ScalaPB](https://scalapb.github.io/) to convert this `.proto` definition into that `FileOptions` scala file. Since that field does exist (even though it is deprecated), I think it is correct that ScalaPB generates a method for this field, marks it deprecated, but still uses it in the serialization/deserialization logic. So even though it's ScalaPB that generates the code that produces this warning, I actually don't think there is anything wrong here.

Now of course it would be better if we had less warnings. It looks like you are building with sbt. Perhaps it would be possible to compile the `ScalaPB`-generated classes without warning about calls to deprecated methods? Of course for our non-generated code we would still like to see this warning.

Would you be interested in giving that a try?

**Comment by drahcrom** [comment]
I'm having this issue as well and would be interested in giving that a try. How exactly would I do this? Do I add it to "scalacOptions" in my build.sbt?

**Comment by raboof** [comment]
That looks good! Another option is to use the `globalFilter` to filter out this message specifically: `"-P:silencer:globalFilters=Marked as deprecated in proto file"` - I guess which approach you prefer is largely a matter of preference.
