### ISSUE TITLE
Reactivate support for Scala 2.11

### ISSUE THREAD

**Issue by derolf** [akka/akka-grpc#547]
I need the server-power-apis to access metadata.

That feature is shipped with 0.6.0, which does not support Scala 2.11 anymore. Please reactivate 2.11 support.

**Comment by raboof** [comment]
Dropping 2.11 support was motivated in #520, mainly since 2.11 is [considered EOL](https://github.com/scala/scala-dev/issues/559#issuecomment-436160166).

I'm curious what's holding you back from moving to 2.12?

**Comment by derolf** [comment]
> I'm curious what's holding you back from moving to 2.12?

We use a company-internal SDK that targets 2.11 because it uses Spark which is still on 2.11. Migration to 2.12 is scheduled later this year.

We are currently building grpc services on top of that SDK with akka-grpc. We need to use 0.6.0 because it allows Metadata access which is required for Auth and extracting user context that is needed inside the service calls.

It looks like it could at least locally we can compile for 2.11 by reverting the "Drop 2.11" patch. So it still works with Scala 2.11 and you could revert to 2.11 if allowed. Or at least publish 0.6.0 with 2.11 support once (to have Metadata support).

As Plan B: Is there any easy way/hack to access Metadata in 0.5.0?

**Comment by raboof** [comment]
Actually Spark support 2.12 since 2.4.0 (out since november), though admittedly they're calling that support 'experimental'.

Indeed if you want to have access to authentication information inside your service implementations the power API would be a suitable way to achieve that (if you only need to block calls you could use the technique demonstrated in #402).

One workaround I could think of that would also work with 0.5.0 would be reconstructing your implementation+handler for each request - I'm curious if that would be slow.

**Comment by raboof** [comment]
I'm afraid we don't plan to re-introduced Scala 2.11 support anymore

**Comment by derolf** [comment]
> I'm afraid we don't plan to re-introduce Scala 2.11 support anymore

Haha :-) The question is 2 years old... We moved on...
