### ISSUE TITLE
akka-grpc-maven-plugin:0.6.0:generate failed: protoc exit code 1: /tmp/protocbridge...

### ISSUE THREAD

**Issue by helena** [akka/akka-grpc#576]
During akka-grpc-maven-plugin:0.6.0:generate, and likely other similar non akka-grpc tasks, if /tmp/ for this process is not accessible, or has the `noexec` mount option set:
```
Execution default of goal com.lightbend.akka.grpc:akka-grpc-maven-plugin:0.6.0:generate failed: protoc exit code 1: /tmp/protocbridge7686600923568091505: program not found or is not executable 
```

Perhaps add a fallback attempt to use the `java.io.tmpdir` to use a directory that doesn't have `noexec` set.

**Comment by jrudolph** [comment]
The problematic code is here:

https://github.com/scalapb/protoc-bridge/blame/master/src/main/scala/protocbridge/frontend/PosixPluginFrontend.scala#L52

If we accept that having a `noexec` `/tmp` directory is common and/or useful, this needs to be fixed upstream.

I'm not actually sure this is worth the effort because the problem only occurs during development and not during runtime.

The workaround is to set `-Djava.io.tmpdir` to an exec'able directory when running the build (sbt/maven/whatever).

What we could try to do in our code is to figure out that the configured `/tmp` directory is indeed marked `noexec` (but how to exactly in a portable way?) and then warn the user and point to the workaround using `-Djava.io.tmpdir`.

**Comment by helena** [comment]
WFM.

**Comment by tiberiu-biking** [comment]
Looks like _noexec_ for _/tmp_ is the default for RedHat 7(maybe only for SELinux ?)
https://access.redhat.com/blogs/766093/posts/1976243
One clean way to fix this is to allow the configuration of the folder via the configuration of the plugin.

**Comment by raboof** [comment]
I can reproduce the issue. To show a bit more of the stack trace:

```
Caused by^[[m: java.lang.RuntimeException: ^[[1;31mprotoc exit code 1: /tmp/protocbridge17693332168925091252: program not found or is not executable
--akka-grpc-javadsl-interface_out: protoc-gen-akka-grpc-javadsl-interface: Plugin failed with status code 1.^[[m
    ^[[1mat^[[m scala.sys.package$.error (^[[1mpackage.scala:26^[[m)
    ^[[1mat^[[m akka.grpc.maven.GenerateMojo.$anonfun$compile$8 (^[[1mGenerateMojo.scala:198^[[m)
    ^[[1mat^[[m akka.grpc.maven.GenerateMojo.$anonfun$compile$8$adapted (^[[1mGenerateMojo.scala:194^[[m)
    ^[[1mat^[[m scala.collection.IndexedSeqOptimized.foreach (^[[1mIndexedSeqOptimized.scala:32^[[m)
    ^[[1mat^[[m scala.collection.IndexedSeqOptimized.foreach$ (^[[1mIndexedSeqOptimized.scala:29^[[m)
    ^[[1mat^[[m scala.collection.mutable.ArrayOps$ofRef.foreach (^[[1mArrayOps.scala:194^[[m)
    ^[[1mat^[[m akka.grpc.maven.GenerateMojo.compile (^[[1mGenerateMojo.scala:194^[[m)
    ^[[1mat^[[m akka.grpc.maven.GenerateMojo.generate (^[[1mGenerateMojo.scala:162^[[m)
    ^[[1mat^[[m akka.grpc.maven.GenerateMojo.$anonfun$execute$1 (^[[1mGenerateMojo.scala:116^[[m)
    ^[[1mat^[[m java.util.ArrayList.forEach (^[[1mArrayList.java:1540^[[m)
    ^[[1mat^[[m akka.grpc.maven.GenerateMojo.execute (^[[1mGenerateMojo.scala:107^[[m)
```

Looks like we can detect when this problem occurs at https://github.com/akka/akka-grpc/blob/master/maven-plugin/src/main/scala/akka/grpc/maven/GenerateMojo.scala#L198, and when it does, we should at least improve the error message to explain what is wrong and suggest using `-Djava.io.tmpdir`.

I'm not sure configuring this via the configuration of the plugin makes sense, since this is a concern around the system on which the build is performed, rather than a concern around the project build itself. That said, I'd definitely be open to investigating whether we can introduce a config option to specify the tmp directory to use from the plugin.

**Comment by stefanobaghino-da** [comment]
Stable link to the problematic code linked above in case someone else ends up here: https://github.com/scalapb/protoc-bridge/blame/e1f490e980d8cb3ea3e454c44a258ed283a1e5c4/src/main/scala/protocbridge/frontend/PosixPluginFrontend.scala#L52

**Comment by patriknw** [comment]
@stefanobaghino-da much has changed here since 2019 so could you give us a full stack trace by running it with `mvn -X`?

I think the place to capture the error is at https://github.com/akka/akka-grpc/blob/8e07c1a72a1c3ed3aa6fe70f09bf5c08722ee401/maven-plugin/src/main/scala/akka/grpc/maven/AbstractGenerateMojo.scala#L226 but I'm not quite sure what to look for or how to reproduce on osx.

**Comment by stefanobaghino-da** [comment]
Hi @patriknw, sorry for the noise, my problem was unrelated to this issue but had a similar symptom. I left the stable link in case anybody else ends up here and wants to understand the conversation, including the link to the problematic code above.

**Comment by johanandren** [comment]
@patriknw I think you could start the JVM with `-Djava.io.tmpdir` pointing to a filesystem mounted with the `noexec` flag, that's probably the tricky part on macos, just permissions on a directory is not enough, perhaps possible by creating an image using disk utility (GUI) and mounting that.

**Comment by johanandren** [comment]
For maven it turns out it is actually no longer a problem with a noexec tmpdir. Not sure if protoc is some other way than executing it directly perhaps.

For sbt this is triggered by the protoc plugin so a more clear error would have to be upstream.

```sbt:akka-grpc-quickstart-scala> last Compile / protocGenerate
[debug] Invalidating cache (input changed)
[info] Compiling 1 protobuf files to /Users/johan/Downloads/akka-grpc-quickstart-scala/target/scala-2.13/akka-grpc/main
[debug] protoc options:
[debug] Compiling schema /Users/johan/Downloads/akka-grpc-quickstart-scala/src/main/protobuf/helloworld.proto
[error] java.lang.RuntimeException: protoc returned exit code: 1
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:464)
[error] 	at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:674)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$17(ProtocPlugin.scala:697)
[error] 	at sbt.util.Difference.apply(Tracked.scala:414)
[error] 	at sbt.util.Difference.apply(Tracked.scala:394)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$16(ProtocPlugin.scala:686)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$16$adapted(ProtocPlugin.scala:682)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$1(ProtocPlugin.scala:710)
```

**Comment by johanandren** [comment]
My bad, I didn't pass the tmpdir sysprop well enough, this is the full exception with maven:

```
Caused by: java.lang.RuntimeException: protoc exit code 1: /Users/johan/akka-grpc-dir/protocbridge5679313815495287748: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--akka-grpc-javadsl-interface_1_out: protoc-gen-akka-grpc-javadsl-interface_1: Plugin failed with status code 1.
    at scala.sys.package$.error (package.scala:30)
    at akka.grpc.maven.AbstractGenerateMojo.$anonfun$compile$9 (AbstractGenerateMojo.scala:272)
    at akka.grpc.maven.AbstractGenerateMojo.$anonfun$compile$9$adapted (AbstractGenerateMojo.scala:262)
    at scala.collection.IndexedSeqOptimized.foreach (IndexedSeqOptimized.scala:36)
    at scala.collection.IndexedSeqOptimized.foreach$ (IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach (ArrayOps.scala:198)
    at akka.grpc.maven.AbstractGenerateMojo.compile (AbstractGenerateMojo.scala:262)
    at akka.grpc.maven.AbstractGenerateMojo.generate (AbstractGenerateMojo.scala:209)
    at akka.grpc.maven.AbstractGenerateMojo.$anonfun$execute$1 (AbstractGenerateMojo.scala:156)
    at java.util.ArrayList.forEach (ArrayList.java:1511)
    at akka.grpc.maven.AbstractGenerateMojo.execute (AbstractGenerateMojo.scala:132)
   ...
```

**Comment by johanandren** [comment]
gradle seems to work fine though
