### ISSUE TITLE
Akka grpc gradle plugin: Could not find akka-grpc-codegen_2.12-assembly.bat

### ISSUE THREAD

**Issue by lukasito** [akka/akka-grpc#636]
### Versions used 
OS: Windows 10 x64
Gradle version: 5.5.1
JDK: 11
com.lightbend.akka.grpc.gradle: 0.7.0

Akka version: 2.5.22

### Expected Behavior
Gradle should be able to recognize the BAT file generated by plugin.

### Actual Behavior
The BAT file that is generated right next to assembly jar in `.gradle/cache` is not recognized by gradle. 

### Relevant logs

> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> Could not resolve all files for configuration ':protobufToolsLocator_akkaGrpc'.
   > Could not find akka-grpc-codegen_2.12-assembly.bat (com.lightbend.akka.grpc:akka-grpc-codegen_2.12:0.7.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/lightbend/akka/grpc/akka-grpc-codegen_2.12/0.7.0/akka-grpc-codegen_2.12-0.7.0-assembly.bat

### How to reproduce

Apply plugin to your gradle project, run `gradlew gP`

**Comment by raboof** [comment]
@mlangc do you know what might be going on here?

**Comment by mlangc** [comment]
I don't know, but I'll take a look at the beginning of next week.

**Comment by lukasito** [comment]
Currently, I see no other way to fix that, except creating local maven repository with bat and jar next to it and add this repository to repositories configuration. E.g.
```groovy
repositories {
  maven {
    url "${project.rootDir}/akkaGrpcRepo"
  }
}
```

**Comment by mlangc** [comment]
When I was working on #622 I've always been using a local maven repo. I didn't know that the gradle cache behaves quite differently, and simply putting a file there is not enough to make it recognized by Gradle. As far as I can see with my very limited Gradle knowledge, there are two possibilities:

1. Find a way to properly add the generated bat file to the gradle cache, so that the dependency gets resolved. The implementation would have to be smart enough to only do this when the associated assembly file also resides there. 
2. Publish the bat file instead of generating it locally. As far as I'm concerned, this seems to be the best solution. If we publish a self contained bat file (that contains the whole assembly), everything should work without any custom hacks - at the cost of some additional storage cost at maven central. If we publish a bat that references the assembly, we should get it to work too, but there might be some corner cases, and we would have to make sure that the assembly always gets downloaded too.

What do you think?

**Comment by raboof** [comment]
Hmm, that sounds rather involved... I wonder if, instead of adding more complexity at 'our side' to work around this, we could somehow fix this 'upstream' somewhere?

**Comment by mlangc** [comment]
Good idea! I'll look into this over the weekend, if there nobody has fixed this till then.

**Comment by lukasito** [comment]
As @mlangc  mentioned, I think that the best solution would be to publish windows binary as [protobuf](https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.9.0/) does.
