### ISSUE TITLE
Gradle-plugin support for Scala 2.13

### ISSUE THREAD

**Issue by tjarvstrand** [akka/akka-grpc#839]
The gradle plugin currently [hard codes a dependency on Scala 2.12](https://github.com/akka/akka-grpc/blob/0c174208a456b6b6fec6869fbf0af53d7a4a02b0/gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy#L143).

Is there any way that the plugin could be cross-built for Scala 2.13 as well? 

We're currently investigating a switch from sbt to gradle but this is unfortunately a showstopper right now.

**Comment by raboof** [comment]
I think that would be an interesting contribution, and I don't see why it wouldn't work: even though the scala code generation (akka-grpc-scalapb-protoc-plugin) will likely have to remain hard-coded to Scala 2.12 (as otherwise the number of combinations would get unweildy), the code it produces should work fine under either 2.12 and 2.13 - so adding an option to the gradle plugin that selects whether to add a dependency to the 2.12 or 2.13 version of the runtime might work.

Until that time, I think I'd also be OK with just switching from 2.12 to 2.13 for the gradle plugin, if you can test this works in practice.

/cc @lukasito @jewertow @hithran @mlangc @orendain @ctoomey who are involved in akka-grpc gradle support

**Comment by tjarvstrand** [comment]
>Until that time, I think I'd also be OK with just switching from 2.12 to 2.13 for the gradle plugin, if you can test this works in practice.

Wouldn't that break it for an awful lot of people?

**Comment by raboof** [comment]
> Wouldn't that break it for an awful lot of people?

I don't know. My impression is that Gradle is mainly used in Java projects, where the Scala version is not really relevant. For the Gradle+Scala population, it seems most of the ecosystem is now available on 2.13, so it might not be so bad?

**Comment by raboof** [comment]
#1042

**Comment by eshepelyuk** [comment]
@raboof is there any ETA for releasing a new plugin version ?

**Comment by raboof** [comment]
We're publishing automatically from master, so version 1.0.0-17-3dcade13 has the updated plugin. Unfortunately I noticed the 2.13 -runtime library was not uploaded correctly for this snapshot, so fixing that (#1050)

**Comment by eshepelyuk** [comment]
But what about non-snapshot version ? The release one.

**Comment by raboof** [comment]
We don't have a set schedule for releasing Akka gRPC, we release whenever there's a good set of features ready. There seems to be a new version of scalapb imminent, perhaps when we have tested these Gradle changes and updated scalapb that might be a nice point to cut 1.0.1?

**Comment by raboof** [comment]
(added https://github.com/akka/akka-grpc/pull/1052 to document this better)
