### ISSUE TITLE
Is akka-grpc supports Publisher/Subscriber pattern?

### ISSUE THREAD

**Issue by Aincvy** [akka/akka-grpc#918]
### Short description
Server play as a Publisher, client play as a Subscriber.
I cannot find anything about it from the internet.
I've tried Source.fromPublisher method, but it seems not working.

### Details

Can I do it now?  
Can I send a message to the client from the server?
If not, will you support it?

Proto file:
```protobuf 
service FightCallService {

    // 
    rpc RoomStatus (ReqRoomStatus) returns (stream ResRoomStatus) {}

}
```

**Comment by raboof** [comment]
I would definitely expect `Source.fromPublisher` to work.

In what way is it not working?

**Comment by Aincvy** [comment]
Here is the part of my code.

#### **`RoomStatusPublisher.java`**
``` java
@Slf4j
public class RoomStatusPublisher implements Publisher<ResRoomStatus> {

    private Subscriber<? super ResRoomStatus> subscriber;

    @Override
    public void subscribe(Subscriber<? super ResRoomStatus> subscriber) {
        this.subscriber = subscriber;
    }

    /**
     * 
     * @param resultReport
     */
    public void putRoomResult(RoomResultReport resultReport) {
        if (resultReport == null || this.subscriber == null) {
            throw null;
        }

        log.debug("publish {}", resultReport);
        // 
        this.subscriber.onNext(FightMessageHelper.convert(resultReport));
        this.subscriber.onComplete();
    }


}
```

#### **`FightCallServiceImpl.java`**
```java
    @Override
    public Source<ResRoomStatus, NotUsed> roomStatus(ReqRoomStatus in, Metadata metadata) {
        var publisher = new RoomStatusPublisher();
        log.debug("roomStatus new publisher");

        return Source.fromPublisher(publisher);
    }
```

#### **`Client.java`**
```java
    public void subscribeRoomStatus(){
        var reqRoomStatus = ReqRoomStatus.newBuilder().build();
        fixAuthHeader(client.roomStatus())
                .invoke(reqRoomStatus)
                .runForeach(this::onRoomStatusResponse,this.materializer);
    }
```

I call `subscribeRoomStatus` when the client starts, and I can receive some messages from the server.
After that, the client do not receive any messages.

**Comment by raboof** [comment]
`FightCallServiceImpl.java` and `Client.java` look fine to me, but `RoomStatusPublisher.java` seems dangerous: implementing `Publisher` yourself comes with a lot of rules (see https://github.com/reactive-streams/reactive-streams-jvm#1-publisher-code), and it's not so obvious that you are fulfilling all those rules here. That interface isn't really intended to be subclassed in your application, usually you'd use a library like Akka Streams instead. A nice article about this is https://blog.softwaremill.com/how-not-to-use-reactive-streams-in-java-9-7a39ea9c2cb3 .

Perhaps you could create a `Source` with `Source.queue` and insert your objects into that rather than using the `putRoomResult` on the `Publisher`.

(this might have been better as a question on https://discuss.akka.io, but OK)

**Comment by Aincvy** [comment]
Hmm, I've tried a search in https://discuss.akka.io, but nothing found.
I am new to Akka, Reactive Streams, I've tried a search about `Publisher default implementation`, it was nothing found too. 
So, I will reorganization content when I finish my question, and put it to the docs(By PR).

`Source.fromPublisher(publisher)` needs a `Publisher`, not a `Flow.Publisher`. So, I try to implement one. I know it's not good now.

I'll try `Source.queue` in next.

By your first comment, can you explain to me how to do with `Source.fromPublisher`.
In your words, it seems to have a way to do that.   
Short words also ok, I'll search it.

**Comment by raboof** [comment]
Your use of `Source.fromPublisher` in `FightCallServiceImpl.java` is correct, but I suspect your `Publisher` implementation is likely wrong. If you'd want to use `Source.fromPublisher`, you'd likely use some library that makes it easy to create a Publisher.

You could even use Akka Streams to create the Publisher: you could create the `Source.queue` like above, and then combine it with `Sink.asPublisher` to get the Publisher, and then `Source.fromPublisher` to turn that back into a `Source`. But that of course would be unnecessarily complicated, since you can use the `Source.queue` directly already without going via `Publisher`.

**Comment by Aincvy** [comment]
After a lot of searches, I found a solution, it can pass a simple test. 

**In short**
I use `source.preMaterialize` method.  link [here](https://stackoverflow.com/a/57659174/11226492)

**Trouble in `Source.queue` and `Sink.asPublisher`**
- The `Source.queue` method returns a `Source[Out, Mat]`. It can't be cast to `Source<ResRoomStatus, NotUsed>`
- `var source =Source.<ResRoomStatus>queue(100, OverflowStrategy.backpressure());`
- The sentence `source.to(Sink.asPublisher(false))` returns `RunnableGraph[+Mat]`.
- `source.to(Sink.asPublisher(false)).run(this.mat)` returns `SourceQueueWithComplete[T]`
- I don't find methods to cast them to `Source<ResRoomStatus, NotUsed>` 

**My solution**
```java
        var source =Source.<ResRoomStatus>queue(100, OverflowStrategy.backpressure());
        var pair = source.preMaterialize(this.mat);
```
Then I return `pair.second()` in method `roomStatus`, and I use `pair.first()` to put element to source.
It works. The client can receive the subsequent messages now.

**Questions**
- Would you implement a simple way to do `send messages from server to client` . If not, would you plan it?

**Comment by raboof** [comment]
> My solution
> 
>        var source = Source.<ResRoomStatus>queue(100, OverflowStrategy.backpressure());
>        var pair = source.preMaterialize(this.mat);

That looks good!

> The Source.queue method returns a `Source[Out, Mat]`. It can't be cast to Source<ResRoomStatus, NotUsed>

You can use either `mapMaterializedValue` or (as you found) `preMaterialize`.

> It works. The client can receive the subsequent messages now.

Good to hear!

> Would you implement a simple way to do `send messages from server to client`. If not, would you plan it?

What would such a simpler way look like?

**Comment by Aincvy** [comment]
`Source.queue` is not thread-safe.


Here is my idea about the simple way.
```java

// session class, may like netty/mina
class GrpcSession {
	
	void send( Message message ) ;
	
	// or 
	
	void sendResRoomStatus(ResRoomStatus message);
	
	void sendResCreateRoom(ResCreateRoom message);
	
	
	// attr
	
	setAttribute(String key, Object obj);
	getAttribute(String key);
	removeAttribute(String key);
	
}


// add this method to generated Service  
void sessionActive(GrpcSession session){

}

void sessionInactive(GrpcSession session ){
	
	
}


//  my service impl   
class MyServiceImpl { 
	
	GrpcSession keepSession;
	
	@Override
	void sessionActive(GrpcSession session){
		this.keepSession = session;
	}

	@Override
	void sessionInactive(GrpcSession session ){
		this.keepSession = null;
	}
	
	
	/**
	 * then , I can call this method to send msg to client.
	 *
	 */
	public void sendMsgToSession (Message msg){
		
		if (keepSession != null ){
			keepSession.send(msg);
		}
	}
	
	
}


```

It‘s maybe too complex.
But I think this or something similar is very useful to send messages to the client.
And does it against grpc's base ideals(base rules)?

**Comment by raboof** [comment]
> I think this or something similar is very useful to send messages to the client.

Yes, being able to stream objects to the client is a key feature of gRPC.

> And does it against grpc's base ideals (base rules)?

The general concept doesn't go against gRPC's paradigm.

As Akka gRPC is built on top of Akka Streams. I think we should make sure Akka Streams can be used to fulfill this use case.

The the API you're describing is not suitable for Akka Streams because an important feature of Akka Streams is that it supports backpressure, and this API doesn't support backpressure.

> Source.queue is not thread-safe.

I know we say this in the API docs, but I think we are a bit too conservative there: IIRC `Source.queue` should be fine if your 'overflowStrategy' is other than 'backpressure'. If it is 'backpressure', there is a new feature planned for Akka 2.6.5 where you could specify the maximum allowed number of concurrent offers, see https://github.com/akka/akka/pull/28273/files#diff-dd7989ad8864b9e69daa0ddc6619e9efR740 .

**Comment by Aincvy** [comment]
> As Akka gRPC is built on top of Akka Streams. I think we should make sure Akka Streams can be used to fulfill this use case.
> 
> The the API you're describing is not suitable for Akka Streams because an important feature of Akka Streams is that it supports backpressure, and this API doesn't support backpressure.

Yeah, it's just my idea. I do not have any experience in using Akka Streams. So, I can't describe to you the simple way with Akka Streams.

**New way of using publisher**
Here is the code.
```java
        var publisher = new SubmissionPublisher<ResRoomStatus>();
        roomManager.setPublisher(publisher);

        return JavaFlowSupport.Source.fromPublisher(publisher);
```
```java
// when I need send message to client
publisher.offer(FightMessageHelper.convert(report), null);
```
It's good to hear `Source.queue` may thread-safe. But I think `SubmissionPublisher` is better now.

**New questions**
- Does the publisher-subscriber-pattern is the only way to send message to client asynchronous？
- I want to add this to the document (new document called FAQ ), what do you think so?

**Comment by raboof** [comment]
> Does the publisher-subscriber-pattern is the only way to send message to client asynchronous?

Well, that depends on where those messages come from: if the source of those messages can already be expressed as a stream, a 'Publisher' API in-between would not be necessary.

> I want to add this to the document (new document called FAQ), what do you think so?

I don't think it belongs in the Akka gRPC documentation, as it is a general Akka Streams use case. It might be interesting to add it as an additional example to the documentation of the `fromPublisher` operator in Akka Streams, though, at https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/stream/operators/Source/fromPublisher.md .

**Comment by Aincvy** [comment]
I think Akka-gRpc's document is insufficient, it does not kind to new.

Maybe you want to keep Akka-gRpc unified, not divided. 
But I still think it needs more documents.
I think Akka-gRpc's learning costs are too high now. If a new one wants to use it, he needs to learn more about Akka-streams.
Maybe Akka-gRpc is designed for Akka's user, if yes, just think I said nothing.

> Well, that depends on where those messages come from: if the source of those messages can 
> already be expressed as a stream, a 'Publisher' API in-between would not be necessary.
Yeah, maybe I have been understood.

Anyways, thank you for help.

**Comment by Aincvy** [comment]
About the doc of `fromPublisher`, I see it now. 
I have missed out on the part `Description`.  :-(
