### ISSUE TITLE
Consider replacing PartialFunction[Request=>Result] with Route 

### ISSUE THREAD

**Issue by raboof** [akka/akka-grpc#991]
Advantages:
* More natural composition of routes

Disadvantages:
* Makes Akka gRPC depend on akka-http, not just akka-http-core
* Does this have performance impact?
* Could cause confusion when people try to pass this to `bindAndHandle` while we haven't implemented https://github.com/akka/akka-http/issues/2463 yet

**Comment by raboof** [comment]
Let's try this in a branch and see what kind of impact it has on cloudstate, that could inform whether this is a good idea.

**Comment by jrudolph** [comment]
After some more consideration, an alternative path could be to simplify interaction between Routes and PartialFunctions like this:

 * You can convert a `PartialFunction` to a `Route` by either rejecting if it doesn't apply or completing with its result. We should provide helpers to do that (maybe as a directive in akka-http).
 * Going the other way round is impossible in general because a route can reject a request asynchronously while a PartialFunction needs make the decision synchronously and can only do the handling asynchronously.
 * That means you can combine Routes and PartialFunctions if you use routes on the outside and PartialFunctions on the inside.
 * Finally, the resulting Route needs to be converted to a handler.

So, what we need is:

 * documented ways to convert PartialFunctions (as provided by akka-grpc) to Routes
 * document the high-level structure (routes on the outside, PFs inside)
 * provide and document APIs to use routes as handlers

**Comment by jrudolph** [comment]
> documented ways to convert PartialFunctions (as provided by akka-grpc) to Routes

Or, we could directly add a new method `def route(...): Route` to the generated handler for easier consumption.

**Comment by raboof** [comment]
AFAICS the approach shown at https://doc.akka.io/docs/akka-grpc/snapshot/server/akka-http.html seems sufficient, especially in conjunction with the changes planned for Akka HTTP 10.2.0 (esp. https://github.com/akka/akka-http/pull/3239 and https://github.com/akka/akka-http/pull/3237)

**Comment by jrudolph** [comment]
That sounds pretty good indeed. But does it really support combining several services? Wouldn't you have to use the `partial` handlers instead of the `apply` one, or otherwise, you will have add redundant routing in your akka-http route as well?

**Comment by raboof** [comment]
> does it really support combining several services

Ah, indeed you'd have to use `partial` and combine them before turning them into a `Route`. Not quite as nice but seems OK for now. Let's add an example of that to that page later (#1023).
